name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

  steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.0"

    - name: Run build app
      run: .scripts/buildprod.sh
